### PR TITLE
FUN192 - Deploy Workspace

### PR DESCRIPTION
**Pull request by nqbao11**

### CODE REVIEW

**Comment by nqbao11** [comment]
[afda47f](https://github.com/FUnigrad/funiverse-app-service/pull/12/commits/afda47f17b62f10c47ab42ce78790df76e176dea)
Lỗi: org.hibernate.boot.registry.selector.spi.StrategySelectionException: Unable to resolve name [org.hibernate.dialect.MySQL57InnoDBDialect] as strategy [org.hibernate.dialect.Dialect] 
image

**Comment by nqbao11** [comment]
Xong phần deploy app-service; connect thành công tới database
image
**Review**
Đã review bởi @uyentrang2247 . Evidence:
image

**To do**
- [x] Fix mvn build
- [x] Connect FE với BE (đang liên hệ anh @nguyentran-se để lấy image FE)

**Comment by nqbao11** [comment]
image
Using separate application.properties successfully

**Comment by nqbao11** [comment]
Done CD
image
image

**Comment by nqbao11** [comment]
Merge đi anh @lomahs  ơi

**Review by lomahs — APPROVED** [review]

**Pull request merged**
